import { Timestamp } from 'firebase/firestore';

export interface IChat {
  userInfo: UserInfo;
  date: DateClass;
}

export interface DateClass {
  seconds: number;
  nanoseconds: number;
}

export interface UserInfo {
  displayName: string;
  uid: string;
  photoURL: string;
}

// -=====

// Generated by https://quicktype.io

export interface IMessage {
  id: string;
  text: string;
  senderId: string;
  date: Timestamp;
  image?: string;
}

export interface DateClass {
  seconds: number;
  nanoseconds: number;
}
